<script>
$(function() {

	$('#cancel').click(function(e) {

		e.preventDefault();
		window.location = '/carrierdiscounts/view';
	});
});
</script>
<link rel="stylesheet" href="/css/carrierdiscounts/carrierdiscounts.css" />

<div class="form-header">Are you sure you want to delete the following Carrier Discount?</div>
<form id="carrierdiscounts-delete-form" class="delete" action="/carrierdiscounts/delete/id/<?php echo $this->carrierDiscount->getId(); ?>" method="post">
	<div class="form-wrapper">
		<label>Company:</label>
		<?php echo $this->carrierDiscount->getCompany_name(); ?>
	</div>
	<div class="form-wrapper">
		<label>Start Date:</label>
		<?php echo $this->carrierDiscount->getStart_date(); ?>
	</div>
	<div class="form-wrapper">
		<label>End Date:</label>
		<?php if (strlen($this->carrierDiscount->getEnd_Date()) !== 0) { echo $this->carrierDiscount->getEnd_date(); } else { echo 'N/A'; } ?>
	</div>
	<div class="form-wrapper">
		<label>Discount:</label>
		<?php echo $this->carrierDiscount->getDiscount(); ?>
	</div>	
	<div class="form-wrapper form-controls">
		<input type="submit" value="Delete" />
		<input id="cancel" type="button" value="Cancel" />
	</div>
</form>