<link rel="stylesheet" href="/css/carrierdiscounts/carrierdiscounts.css" />

<form id="carrierdiscounts-entry-form" action="/carrierdiscounts/<?php echo $this->type; ?>" method="post">
	<?php if ($this->type === 'edit') { ?>
		<input type="hidden" name="id" value="<?php echo $this->params['id']; ?>" />
	<?php } ?>
	<div class="form-wrapper">
		<label for="company_id">Company:</label>
		<select name="company_id">
			<option></option>
			<?php 
			
			foreach ($this->customers() as $item) {
 
				if (isset($this->params['company_id']) && $this->params['company_id'] == $item->getCustomer_id()) {
					
					echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
				}
				else {
					
					echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
				}   		
    		}
    		
    		?>
		</select>
	</div>
	<?php if (isset($this->errors['company_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['company_id']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="start_date">Start Date:</label>
		<input type="text" name="start_date" class="datepicker" 
			<?php if (isset($this->params['start_date'])) { echo 'value="' . $this->params['start_date'] . '"'; } ?> />
	</div>
	<?php if (isset($this->errors['start_date'])) { ?><div class="error-wrapper"><?php echo $this->errors['start_date']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="end_date">End Date:</label>
		<input type="text" name="end_date" class="datepicker" 
			<?php if (isset($this->params['end_date'])) { echo 'value="' . $this->params['end_date'] . '"'; } ?> />
	</div>
	<?php if (isset($this->errors['end_date'])) { ?><div class="error-wrapper"><?php echo $this->errors['end_date']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="asset_name">Discount:</label>
		<input type="text" name="discount" class="numeric" maxlength="3" size="3"
			<?php if (isset($this->params['discount'])) { echo 'value="' . $this->params['discount'] . '"'; } ?> />
	</div>
	<?php if (isset($this->errors['discount'])) { ?><div class="error-wrapper"><?php echo $this->errors['discount']; ?></div><?php } ?>
	<div class="form-wrapper form-controls">
		<input type="submit" value="<?php echo ucfirst($this->type); ?> Carrier Discount" />
	</div>
</form>