<tbody>
<?php foreach ($this->carrierDiscounts as $item) { ?>	
	<tr>
		<td><?php echo $item->getCompany_name(); ?></td>
		<td><?php echo $item->getStart_date(); ?></td>
		<td><?php echo $item->getEnd_date(); ?></td>
		<td><?php echo $item->getDiscount(); ?></td>
		<td><a href="/carrierdiscounts/edit/id/<?php echo $item->getId(); ?>">Edit</a></td>
		<td><a href="/carrierdiscounts/delete/id/<?php echo $item->getId(); ?>">Delete</a></td>
	</tr>
<?php } ?>
</tbody>