<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/carrierdiscounts/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />

<table class="tableh">
	<thead>
		<tr>
			<th column="c.name">
				<div class="header">Company</div>
				<div class="sort asc"></div>
			</th>
			<th column="cd.start_date">
				<div class="header">Start Date</div>
				<div class="sort"></div>
			</th>
			<th column="cd.end_date">
				<div class="header">End Date</div>
				<div class="sort"></div>
			</th>
			<th column="cd.discount">
				<div class="header">Discount</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/carrierdiscounts/tabulardata.phtml', array('carrierDiscounts' => $this->carrierDiscounts)); ?>
</table>