<tbody>
<?php foreach ($this->loads as $item) {?>
	<tr id="load_id-<?php echo $item->getLoad_id()?>">
		
		<td class="disp-load-select">
			<span class="ui-icon ui-icon-circle-plus qb-select-load" load_id="<?php echo $item->getLoad_id()?>"></span>
		</td>
		<td width="35">
			<div style="float:left" class="qb-email-invoice" load_id="<?php echo $item->getLoad_id()?>" email="<?php echo $item->getEmail_invoice();?>">
				<span class="ui-icon ui-icon-mail-closed ui-icon-arrowthick-1-ne "></span>
			</div>
			<div class="qb-email-invoice" style="float:right;<?php if($item->getEmail_invoice() !=1){echo 'display:none"';}?>">
				<span class="ui-icon ui-icon-arrowthick-1-ne" ></span>
			</div>
		</td>
		<td class="qb-invoice_date color-block"> <?php echo $item->getInvoice_date(); ?></td>
		<td class="disp-order-number"><?php echo $item->getOrder_number();?></td>
		<td class="qb-carrier color-block" style="background-color:#<?php echo $item->getCarrier_color();?>"><div ><?php echo $item->getCarrier(); ?></div></td>
		<td class="qb-bill_to color-block" style="background-color:#<?php echo $item->getBill_to_color();?>"><div ><?php echo $item->getBill_to(); ?></div></td>
		<td class="qb-shipper color-block" style="background-color:#<?php echo $item->getShipper_color();?>"><div><?php echo $item->getShipper(); ?></div></td>
		<td class="qb-orgin color-block" style="background-color:#<?php echo $item->getOrigin_color();?>"><div ><?php echo $item->getOrigin()?></div></td>
		<td class="qb-customer color-block" style="background-color:#<?php echo $item->getCustomer_color();?>"><div ><?php echo $item->getCustomer(); ?></div></td>
		<td class="qb-destination color-block" style="background-color:#<?php echo $item->getDestination_color();?>"><div><?php echo $item->getDestination(); ?></div></td>
		<td class="qb-delivery_date"> <?php echo $this->formatdate($item->getDelivery_date()); ?></td>
		<td class="qb-bill_of_lading"> <?php echo $item->getBill_of_lading(); ?></td>
		<td class="qb-net_gallons"> <?php echo $item->getNet_gallons(); ?></td>
		<td class="qb-fuel_surcharge"> <?php echo $item->getFuel_surcharge(); ?></td>
		<td class="qb-bill_rate"><?php echo $item->getBill_rate();?></td>
		<td class="qb-discount"> <?php echo $item->getDiscount(); ?></td>

		<td><div class="qb-edit ui-icon ui-icon-pencil" load_id="<?php echo $item->getLoad_id()?>">edit</div></td>
	</tr>

<?php } ?>

</tbody>

