
<form id="rate-entry-form" action="/quickbooks/verifyloads?search" method="post">
<table>
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label for="carrier_id">Carrier:</label>
				<select name="carrier_id">
					<option></option>
					<?php 
					
					foreach ($this->carriers() as $item) {
		 
						if (isset($this->params['carrier_id']) && $this->params['carrier_id'] === $item->getCustomer_id()) {
							
							echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
						}
						else {
							
							echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
						}   		
		    		}
		    		
		    		?>
				</select>
			</div>
		
		</td>
		
		
		<td>
			<div class="form-wrapper">
			<label for="bill_to_id">Bill To:</label>
			<select name="bill_to_id">
				<option></option>
				<?php 
				
				foreach ($this->billtos() as $item) {
	 
					if (isset($this->params['bill_to_id']) && $this->params['bill_to_id'] === $item->getCustomer_id()) {
						
						echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
					}
					else {
						
						echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
					}   		
	    		}
	    		
	    		?>
			</select>
		</div>
		</td>
	</tr>
	
		<tr>
	
		<td>
			<div class="form-wrapper">
				<label for="shipper_id">Shipper:</label>
				<select name="shipper_id">
					<option></option>
					<?php 
					
					foreach ($this->shippers() as $item) {
		 
						if (isset($this->params['shipper_id']) && $this->params['shipper_id'] === $item->getCustomer_id()) {
							
							echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
						}
						else {
							
							echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
						}   		
		    		}
		    		
		    		?>
				</select>
			</div>
		
		</td>
		
		
		<td>
			<div class="form-wrapper">
			<label for="customer_id">Customer:</label>
			<select name="customer_id">
				<option></option>
				<?php 
				
				foreach ($this->customers() as $item) {
	 
					if (isset($this->params['customer_id']) && $this->params['customer_id'] === $item->getCustomer_id()) {
						
						echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
					}
					else {
						
						echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
					}   		
	    		}
	    		
	    		?>
			</select>
		</div>
		</td>
	</tr>
	
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label for="origin_id">Origins:</label>
				<select name="origin_id">
					<option></option>
					<?php 
					
					foreach ($this->origins() as $item) {
		 
						if (isset($this->params['origin_id']) && $this->params['origin_id'] === $item->getCustomer_id()) {
							
							echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
						}
						else {
							
							echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
						}   		
		    		}
		    		
		    		?>
				</select>
			</div>
		
		</td>
		
		
		<td>
			<div class="form-wrapper">
			<label for="destination_id">Destination:</label>
			<select name="destination_id">
				<option></option>
				<?php 
				
				foreach ($this->destinations() as $item) {
	 
					if (isset($this->params['destination_id']) && $this->params['destination_id'] === $item->getCustomer_id()) {
						
						echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
					}
					else {
						
						echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
					}   		
	    		}
	    		
	    		?>
			</select>
		</div>
		</td>
	</tr>
	
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label for="origin_id_location">Origin Location:</label>
				<select name="origin_id_location">
					<option></option>
					<?php 
					
					foreach ($this->origins() as $item) {
		 
						if (isset($this->params['origin_id']) && $this->params['origin_id'] === $item->getCustomer_id()) {
							
							echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getCity() . ' '.$item->getState().'</option>';
						}
						else {
							
							echo '<option value="' . $item->getCustomer_id() . '">' . $item->getCity() . ' '.$item->getState(). '</option>';
						}   		
		    		}
		    		
		    		?>
				</select>
			</div>
		
		</td>
		
		
		<td>
			<div class="form-wrapper">
			<label for="destination_id">Destination Location:</label>
			<select name="destination_id">
				<option></option>
				<?php 
				
				foreach ($this->destinations() as $item) {
	 
					if (isset($this->params['destination_id_location']) && $this->params['destination_id_location'] === $item->getCustomer_id()) {
						
						echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getCity() . ' '.$item->getState(). '</option>';
					}
					else {
						
						echo '<option value="' . $item->getCustomer_id() . '">'. $item->getCity() . ' '.$item->getState().'</option>';
					}   		
	    		}
	    		
	    		?>
			</select>
		</div>
		</td>
	</tr>
	
	
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label>Delivery Date:</label>
					<input type="text" name="delivery_start_date" class="datepicker" />
							to
					<input type="text" name="delivery_end_date" class="datepicker"  />
			</div>	
		
		</td>
		
		<td>
			<div class="form-wrapper">
				<label>Invoice Date:</label>
					<input type="text" name="invoice_start_date" class="datepicker" />
							to
					<input type="text" name="invoice_end_date" class="datepicker"  />
			</div>	
		
		</td>
	</tr>
	
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label>Order Number</label>
					<input type="text" name="order_number"/>
			</div>	
		
		</td>
		
		<td>
			<div class="form-wrapper">
				<label>Net Gallons:</label>
					<input type="text" name="net_gallons_start" />
							to
					<input type="text" name="net_gallons_end"/>
			</div>	
		
		</td>
	
	</tr>
	
	<tr>
	
		<td>
			<div class="form-wrapper">
				<label>BOL #</label>
					<input type="text" name="bill_of_lading"/>
			</div>	
		
		</td>
	
	</tr>
	
	<tr>
		<td>
		<button type="submit">Search</button>
		<button type="reset">Reset</button>
		</td>
	</tr>
	

</table>
</form>
