<style>

</style>

<div>
<table id="disp-modal-tbl">
	<thead>
		<tr>
			<th>Delayed</th>
			<th>Shipper</th>
			<th>Origin</th>
			<th>Destination</th>
			<th>Customer</th>
			<th>Order<br>Number</th>
			<th>Dispatch<br>Order</th>
			<th>Bill<br>Rate</th>
			<th>Fuel<br>Surcharge</th>
			
		</tr>
	</thead>
	<tbody id="disp-modal">	
		
	</tbody>

</table>

</div>
<div></div>
<select class="bill-rate">
		<option value=""></option>
		<option value="0">Other...</option>
</select>

<select class="fuel-surcharge">
	<option value=""></option>
	<option value="0">Other...</option>
</select>
<input class="dispatch-order" MAXLENGTH="3" size="4"></input>
<script>
ldlck._dispatch_modal();
</script>
