<tbody>
<?php foreach ($this->data as $item) { ?>
	<tr>
		<td><input class="emp-select" type="radio" name="emp_group" emp_id="<?php echo $item->getEmp_id();?>" compartments="<?php echo $item->getCompartments();?>" emp_name="<?php echo $item->getLast_name().', '.$item->getFirst_name(); ?>"></input></td>
		<td><?php echo $item->getLast_name().', '.$item->getFirst_name(); ?></td>
		<td><?php echo $item->getDispatched_loads(); ?></td>
		<td><?php echo $item->getPending_loads(); ?></td>
		<td></td>
	</tr>
<?php } ?>
</tbody>