<link rel="stylesheet" href="/css/assettypes/assettypes.css" />
<script src="/js/assettypes/assettypes.js"></script>

<table>
<thead>
	<tr>
		<th>Asset Type</th>
		<th>Active</th>
		<th>Description</th>
		<th></th>
		<th></th>
	</tr>
</thead>
<tbody>
<?php foreach($this->assetTypes as $item) { ?>
	<tr>
		<td><?php echo $item->getAsset_type(); ?></td>
		<td><?php echo $item->getActive(); ?></td>
		<td><?php echo $item->getDescription(); ?></td>
		<td><a href="/assettypes/edit/asset_type_id/<?php echo $item->getAsset_type_id(); ?>">Edit</a></td>
		<td><a href="/assettypes/delete/asset_type_id/<?php echo $item->getAsset_type_id(); ?>">Delete</a></td>
	</tr>
<?php } ?>
</tbody>
</table>