<script>
$(function() {

	$('#cancel').click(function(e) {

		e.preventDefault();
		window.location = '/assets/view';
	});
});
</script>
<link rel="stylesheet" href="/css/assets/assets.css" />

<div class="form-header">Are you sure you want to delete the following Asset?</div>
<form id="assets-delete-form" class="delete" action="/assets/delete/asset_id/<?php echo $this->asset->getAsset_id(); ?>" method="post">
	<div class="form-wrapper">
		<label>Asset Type:</label>
		<?php echo $this->asset->getAsset_type(); ?>
	</div>
	<div class="form-wrapper">
		<label>Asset:</label>
		<?php echo $this->asset->getAsset_name(); ?>
	</div>
	<div class="form-wrapper">
		<label>Compartment Count:</label>
		<?php echo $this->asset->getCompartment_count(); ?>
	</div>
	<div class="form-wrapper">
		<label>Active:</label>
		<?php if ($this->asset->getActive() === 1) { echo 'Y'; } else { echo 'N'; } ?>
	</div>	
	<div class="form-wrapper">
		<label>Customer:</label>
		<?php echo $this->asset->getCustomer_name(); ?>
	</div>
	<div class="form-wrapper">
		<label>Navman Vehicle ID:</label>
		<?php if (strlen($this->asset->getNavman_vehicle_id()) > 0) { echo $this->asset->getNavman_vehicle_id(); } else { echo 'N/A'; } ?>
	</div>
	<div class="form-wrapper form-controls">
		<input type="submit" value="Delete" />
		<input id="cancel" type="button" value="Cancel" />
	</div>
</form>