<tbody>
<?php foreach ($this->assets as $item) { ?>	
	<tr>
		<td><?php echo $item->getAsset_name(); ?></td>
		<td><?php echo $item->getAsset_type(); ?></td>
		<td><?php echo $item->getCompartment_count(); ?></td>
		<td><?php if ($item->getActive() === 1) { echo 'Y'; } else { echo 'N'; } ?></td>
		<td><?php echo $item->getCustomer_name(); ?></td>
		<td><?php echo $item->getNavman_vehicle_id(); ?></td>
		<td><a href="/assets/edit/asset_id/<?php echo $item->getAsset_id(); ?>">Edit</a></td>
		<td><a href="/assets/delete/asset_id/<?php echo $item->getAsset_id(); ?>">Delete</a></td>
	</tr>
<?php } ?>
</tbody>