<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/assets/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />

<table class="tableh">
	<thead>
		<tr>
			<th column="tbl_asset.asset_name">
				<div class="header">Asset Name</div>
				<div class="sort asc"></div>
			</th>
			<th column="tbl_asset_type.asset_type">
				<div class="header">Asset Type</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_asset.compartment_count">
				<div class="header">Compartment Count</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_asset.active">
				<div class="header">Active</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_customer.name">
				<div class="header">Customer</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_asset.navman_vehicle_id">
				<div class="header">Navman Vehicle ID</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/assets/tabulardata.phtml', array('assets' => $this->assets)); ?>
</table>