<table>
	<thead>
		<tr>
			<th>Asset Name</th>
			<th>Asset Type</th>
			<th>Compartment Count</th>
			<th>Active</th>
			<th>Customer</th>
			<th>Navman Vehicle ID</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->assets as $item) { ?>	
		<tr>
			<td><?php echo $item->getAsset_name(); ?></td>
			<td><?php echo $this->assetTypes[$item->getAsset_type_id()]->getAsset_type(); ?></td>
			<td><?php echo $item->getCompartment_count(); ?></td>
			<td><?php echo $item->getActive(); ?></td>
			<td><?php echo $this->customers[$item->getCustomer_id()]->getName(); ?></td>
			<td><?php echo $item->getNavman_vehicle_id(); ?></td>
			<td><a href="/assets/edit/asset_id/<?php echo $item->getAsset_id(); ?>">Edit</a></td>
			<td><a href="/assets/delete/asset_id/<?php echo $item->getAsset_id(); ?>">Delete</a></td>
		</tr>
	<?php } ?>
	</tbody>
</table>