<table>
	<thead>
		<tr>
			<th>Carrier</th>
			<th>Bill To</th>
			<th>Shipper</th>
			<th>Origin</th>
			<th>Origin Location</th>
			<th>Customer</th>
			<th>Destination</th>
			<th>Destination Location</th>
			<th>Product</th>
			<th>Load Date</th>
			<th>Drive</th>
			<th>Delivery Date</th>
			<th>Order #</th>
			<th>Bill of Lading</th>
			<th>Net Gallons</th>
			<th>Rate</th>
			<th>Discount</th>
			<th>Fuel Surcharge</th>
			<th></th>
			<th>All</th>
		</tr>
	</thead>
	<tbody>
		
	</tbody>
</table>
