<tbody>
<?php foreach ($this->loads as $item) { ?>
	<tr>
		<td><div style="background-color:#<?php echo $item->getCarrier_color();?>"><?php echo $item->getCarrier(); ?></div></td>
		<td><?php echo $item->getBill_to(); ?></td>
		<td><?php echo $item->getShipper(); ?></td>
		<td><?php echo $item->getOrigin(); ?></td>
		<td><?php echo $item->getCustomer(); ?></td>
		<td><?php echo $item->getDestination(); ?></td>
		<td><?php echo $item->getProduct(); ?></td>
		<td><?php echo $item->getDriver(); ?></td>
		<td><?php echo $item->getDelayed_dispatch(); ?></td>
		<td><?php echo $item->getLoad_date() . ' ' . $item->getLoad_time(); ?></td>
		<td><?php echo $item->getDelivery_date() . ' ' . $item->getDelivery_time(); ?></td>
		<td><?php echo $item->getOrder_number(); ?></td>
		<td><?php echo $item->getBill_of_lading(); ?></td>
		<td><?php echo $item->getNet_gallons(); ?></td>
		<td><?php echo $item->getBill_rate(); ?></td>
		<td><?php echo $item->getFuel_surcharge(); ?></td>
		<td><?php echo $item->getDiscount(); ?></td>
		<td><?php echo $item->getInvoice_date(); ?></td>
		<td><?php echo $item->getDispatched(); ?></td>
		<td><?php echo $item->getNotes(); ?></td>
		<td><?php echo $item->getLoad_locked(); ?></td>
		<td><?php echo $item->getDelivered(); ?></td>
		<td><?php echo $item->getActive(); ?></td>
		<td><a href="/standardloads/editload/load_id/<?php echo $item->getLoad_id(); ?>">Edit</a></td>
		<td><a href="/standardloads/delete/load_id/<?php echo $item->getLoad_id(); ?>">Delete</a></td>
	</tr>
<?php } ?>
</tbody>
