<tbody>
<?php foreach ($this->loads as $item) { ?>
	<tr>
		<td><?php echo $this->pswcustomers($item->getCarrier_id())->getName(); ?></td>
		<td><?php echo $this->pswcustomers($item->getBill_to_id())->getName(); ?></td>
		<td><?php echo $this->pswcustomers($item->getShipper_id())->getName(); ?></td>
		<td>
			<?php 
			
			$origin = $this->pswcustomers($item->getOrigin_id());			
			$displayVal = '';
			
			if ($origin->getName() !== '') {
					
				$displayVal = $origin->getCity() . ', ' . $origin->getState() . ' - ' . $origin->getName();
			}
			else {
					
				$displayVal = $origin->getCity() . ', ' . $origin->getState();
			}
			
			echo $displayVal; 
				
			?>
		</td>
		<td><?php echo $this->pswcustomers($item->getCustomer_id())->getName(); ?></td>
		<td>
			<?php 
			
			$destination = $this->pswcustomers($item->getDestination_id());
			$displayVal = '';
			
			if ($destination->getCity() !== '' && $destination->getState() !== '' && $destination->getName() !== '') {
					
				$displayVal = $destination->getCity() . ', ' . $destination->getState() . ' - ' . $destination->getName();
			}
			else if ($destination->getCity() !== '' && $destination->getState() !== '') {
					
				$displayVal = $destination->getCity() . ', ' . $destination->getState();
			}
			else if ($destination->getCity() !== '') {
				
				$displayVal = $destination->getCity();
			}
			else if ($destination->getState() !== '') {
				
				$displayVal = $destination->getState();
			}
			else if ($destination->getName() !== '') {
				
				$displayVal = $destination->getName();
			}

			echo $displayVal;
			
			?>
		</td>
		<td><?php echo $item->getProduct_id(); ?></td>
		<td><?php echo $item->getDriver_id(); ?></td>
		<td><?php echo $item->getDelayed_dispatch(); ?></td>
		<td><?php echo $item->getLoad_date() . ' ' . $item->getLoad_time(); ?></td>
		<td><?php echo $item->getDelivery_date() . ' ' . $item->getDelivery_time(); ?></td>
		<td><?php echo $item->getOrder_number(); ?></td>
		<td><?php echo $item->getBill_of_lading(); ?></td>
		<td><?php echo $item->getNet_gallons(); ?></td>
		<td><?php echo $item->getBill_rate(); ?></td>
		<td><?php echo $item->getFuel_surcharge(); ?></td>
		<td><?php echo $item->getDiscount(); ?></td>
		<td><?php echo $item->getInvoice_date(); ?></td>
		<td><?php echo $item->getDispatched(); ?></td>
		<td><?php echo $item->getNotes(); ?></td>
		<td><?php echo $item->getLoad_locked(); ?></td>
		<td><?php echo $item->getDelivered(); ?></td>
		<td><a href="/standardloads/edit/load_id/<?php echo $item->getLoad_id(); ?>">Edit</a></td>
		<td><a href="/standardloads/delete/load_id/<?php echo $item->getLoad_id(); ?>">Delete</a></td>
	</tr>
<?php } ?>
</tbody>