<link rel="stylesheet" href="/css/reminders/reminders.css" />

<form id="rate-entry-form" action="/rates/<?php echo $this->type; ?>" method="post">
	<?php if ($this->type === 'edit') { ?><input type="hidden" name="rate_id" value="<?php echo $this->rate_id; ?>" /><?php } ?>
	<div class="form-wrapper">
		<label for="bill_to_id">Bill To:</label>
		<select name="bill_to_id">
			<option></option>
			<?php 
			
			foreach ($this->billtos() as $item) {
 
				if (isset($this->params['bill_to_id']) && $this->params['bill_to_id'] === $item->getCustomer_id()) {
					
					echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
				}
				else {
					
					echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
				}   		
    		}
    		
    		?>
		</select>
	</div>
	<?php if (isset($this->errors['bill_to_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['bill_to_id']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="origin_id">Origin:</label>
		<select name="origin_id">
			<option></option>
			<?php 
			
			foreach ($this->Origins() as $item) {
 
				if (isset($this->params['origin_id']) && $this->params['origin_id'] === $item->getCustomer_id()) {
					
					echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
				}
				else {
					
					echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
				}   		
    		}
    		
    		?>
		</select>
	</div>
	<?php if (isset($this->errors['origin_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['origin_id']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="destination_id">Destination:</label>
		<select name="destination_id">
			<option></option>
			<?php 
			foreach ($this->Destinations() as $item) {
				if (isset($this->params['destination_id']) && $this->params['destination_id'] === $item->getCustomer_id()) {
					
					echo '<option value="' . $item->getCustomer_id() . '" selected>' . $item->getName() . '</option>';
				}
				else {
					
					echo '<option value="' . $item->getCustomer_id() . '">' . $item->getName() . '</option>';
				}   		
    		}

    		
    		?>
		</select>
	</div>
	<?php if (isset($this->errors['destination_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['destination_id']; ?></div><?php } ?>

	<div class="form-wrapper">
		<label for="route_type_id">Route Type:</label>
		<select name="route_type_id">
			<option></option>
			<?php 
				foreach($this->RouteTypes()as $k => $v)
				{
					if (isset($this->params['route_type_id']) && $this->params['route_type_id'] == $k) {
						echo '<option value="'.$k.'" selected>'.$v.'</option>';
					}
					else
					{
						echo '<option value="'.$k.'">'.$v.'</option>';
					}
				}					
    		?>
		</select>

	</div>
	<?php if (isset($this->errors['route_type_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['route_type_id']; ?></div><?php } ?>
	
	
	<div class="form-wrapper">
		<label for="start_date">Effective Date:</label>
		<input type="text" name="start_date" class="datepicker" <?php if (isset($this->params['start_date']) && !isset($this->errors)) { echo 'value="' . $this->formatDate($this->params['start_date']) . '"'; } ?>
															  <?php if (isset($this->params['start_date']) && isset($this->errors)) { echo 'value="' . $this->params['start_date'] . '"'; } ?> />
	</div>	
	<?php if (isset($this->errors['start_date'])) { ?><div class="error-wrapper"><?php echo $this->errors['start_date']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="rate">Rate:</label>
		<input type="text" name="rate" <?php if (isset($this->params['rate'])&&!isset($this->errors)){echo 'value="'.$this->params['rate'].'"';}?>/>
	
	</div>
	<?php if (isset($this->errors['rate'])) { ?><div class="error-wrapper"><?php echo $this->errors['rate']; ?></div><?php } ?>
	
	<div class="form-wrapper form-controls">
		<input type="submit" value="<?php echo ucfirst($this->type); ?> Rate" />
	</div>

</form>