<script>
$(function() {
	
	if ($('#username')) {
		
		$('#username').focus();
	}	
});

$(document).ready(function() {
	
	$('#show-hide-comm-options').toggle(function() {
		
		$(this).html('- Communication Options');
		$('#comm-options').show();
	}, function() {
		
		$(this).html('+ Communication Options');
		$('#comm-options').hide();
	});

	$('#phone').bind('blur keyup', function() {
		
		if ($(this).val().length === 0) {
			
			$('#phone_primary').attr({ 'checked': false, 'disabled': true });			
		}
		else {
			
			$('#phone_primary').removeAttr('disabled');
		}		
	});
	
	$('#phone_primary').click(function() {
		
		if ($('#cell_phone_primary').is(':checked')) {
			
			$('#cell_phone_primary').attr('checked', false);
		}
	});
	
	$('#cell_phone').bind('blur keyup', function() {
		
		if ($(this).val().length === 0) {
			
			$('#cell_phone_primary').attr({ 'checked': false, 'disabled': true });			
		}
		else {
			
			$('#cell_phone_primary').removeAttr('disabled');
		}		
	});
	
	$('#cell_phone_primary').click(function() {
		
		if ($('#phone_primary').is(':checked')) {
			
			$('#phone_primary').attr('checked', false);
		}
	});
});
</script>
<link rel="stylesheet" href="/css/employees/employees.css">

<form id="employees-entry-form" action="/employees/<?php echo $this->type; ?>" method="post">
	<?php if ($this->type === 'edit') { ?><input type="hidden" name="emp_id" value="<?php echo $this->empId; ?>" /><?php } ?>
	<div class="form-wrapper">
		<label for="username">Username:</label>
		<?php if ($this->type === 'add') { ?>
		<input type="text" name="username" maxlength="20" size="20"
			<?php if (isset($this->params['username'])) { echo 'value="' . $this->params['username'] . '"'; } ?> />
		<?php } else { echo $this->params['username']; } ?>
	</div>
	<?php if (isset($this->errors['username'])) { ?><div class="error-wrapper"><?php echo $this->errors['username']; ?></div><?php } ?>
	<?php if ($this->type === 'edit') { ?>
	<div class="form-wrapper">Only enter a password and confirmation password when changing the password.</div>
	<?php } ?>
	<div class="form-wrapper">
		<label for="password">Password:</label>
		<input type="password" name="password" maxlength="100" />
	</div>
	<?php if (isset($this->errors['password'])) { ?><div class="error-wrapper"><?php echo $this->errors['password']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="confpass">Confirm Password:</label>
		<input type="password" name="confpass" maxlength="100" />
	</div>
	<?php if (isset($this->errors['confpass'])) { ?><div class="error-wrapper"><?php echo $this->errors['confpass']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="first_name">First Name:</label>
		<input type="text" name="first_name" maxlength="256" 
			<?php if (isset($this->params['first_name'])) { echo 'value="' . $this->params['first_name'] . '"'; }?> maxlength="256" />
	</div>
	<div class="form-wrapper">
		<label for="last_name">Last Name:</label>
		<input type="text" name="last_name" maxlength="256" 
			<?php if (isset($this->params['last_name'])) { echo 'value="' . $this->params['last_name'] . '"'; }?> maxlength="256" />
	</div>
	<div class="form-wrapper">
		<label for="email">E-mail:</label>
		<input type="text" name="email" maxlength="256" 
			<?php if (isset($this->params['email'])) { echo 'value="' . $this->params['email'] . '"'; }?> maxlength="256" size="30" />
	</div>
	<?php if (isset($this->errors['email'])) { ?><div class="error-wrapper"><?php echo $this->errors['email']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="addr">Address:</label>
		<input type="text" name="addr" maxlength="256" 
			<?php if (isset($this->params['addr'])) { echo 'value="' . $this->params['addr'] . '"'; }?> maxlength="256" size="30" />
	</div>
	<div class="form-wrapper">
		<label for="addr">Address Line 2:</label>
		<input type="text" name="addr2" maxlength="256" 
			<?php if (isset($this->params['addr2'])) { echo 'value="' . $this->params['addr'] . '"'; }?> maxlength="256" size="30" />
	</div>
	<div class="form-wrapper">
		<label for="city">City:</label>
		<input type="text" name="city" maxlength="60"
			<?php if (isset($this->params['city'])) { echo 'value="' . $this->params['city'] . '"'; }?> maxlength="60" />
	</div>	
	<div class="form-wrapper">
		<label for="state">State:</label>
		<select name="state">
			<option></option>
			<?php 
				
			foreach ($this->pswstates() as $key => $value) {
 
				if (isset($this->params['state']) && $this->params['state'] === $key) {
						
					echo '<option value="' . $key . '" selected>' . $value . '</option>';
				}
				else if (!isset($this->state) && $key === 'MO') {
						
					echo '<option value="' . $key . '" selected>' . $value . '</option>';
				}
				else {
						
					echo '<option value="' . $key . '">' . $value . '</option>';
				}
    		}
    			    			
    		?>
		</select>
	</div>	
	<div class="form-wrapper">
		<label for="zip">Zip:</label>
		<input type="text" name="zip" class="numeric" 
			<?php if (isset($this->params['zip'])) { echo 'value="' . $this->params['zip'] . '"'; }?> maxlength="5" size="5" /> -
		<input type="text" name="zip4" class="numeric" 
			<?php if (isset($this->params['zip4']) && $this->params['zip4'] !== 0) { echo 'value="' . $this->params['zip4'] . '"'; }?> maxlength="4" size="4" />
	</div>	
	<?php if (isset($this->errors['zip'])) { ?><div class="error-wrapper"><?php echo $this->errors['zip']; ?></div><?php } ?>
	<?php if (isset($this->errors['zip4'])) { ?><div class="error-wrapper"><?php echo $this->errors['zip4']; ?></div><?php } ?>
	<div class="form-wrapper">
		<label for="active">Role:</label>
		<select name="role_id">
			<option></option>
			<?php 
				
			foreach ($this->roles() as $item) {
 
				if (isset($this->params['role_id']) && $this->params['role_id'] == $item->getRole_id()) {
						
					echo '<option value="' . $item->getRole_id() . '" selected>' . $item->getRole_name() . '</option>';
				}
				else {
					
					echo '<option value="' . $item->getRole_id() . '">' . $item->getRole_name() . '</option>';
				}
    		}
    			
    		?>
		</select>
	</div>
	<?php if (isset($this->errors['role_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['role_id']; ?></div><?php } ?>
	<?php if ($this->type === 'edit') { ?>
	<div class="form-wrapper">
		<label for="active">Active:</label>
		<input type="checkbox" name="active"
			<?php if (isset($this->params['active']) && $this->params['active']) { echo 'checked'; }?> />
	</div>	
	<?php } ?>
	<div class="form-wrapper">
		<label for="active">User Type:</label>
		<select name="user_type_id">
			<option></option>
			<?php 
				
			foreach ($this->userTypes() as $item) {
 
				if (isset($this->params['user_type_id']) && $this->params['user_type_id'] === $item->getUser_type_id()) {
						
					echo '<option value="' . $item->getUser_type_id() . '" selected>' . $item->getUser_type() . '</option>';
				}
				else {
						
					echo '<option value="' . $item->getUser_type_id() . '">' . $item->getUser_type() . '</option>';
				}
    		}
    			
    		?>
		</select>
	</div>	
	<?php if (isset($this->errors['user_type_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['user_type_id']; ?></div><?php } ?>
	<div id="comm-options-wrapper">
		<div id="show-hide-comm-options">+ Communication Options</div>
		<div id="comm-options">
			<div class="form-wrapper">
				<label for="phone">Phone #:</label>
				<input type="text" id="phone" name="phone" class="numeric phone" 
					<?php if (isset($this->params['phone'])) { echo 'value="' . $this->params['phone'] . '"'; }?> />
				<label for="phone_ext" class="no-float">Ext:</label>
				<input type="text" name="phone_ext" class="numeric" 
					<?php if (isset($this->params['phone_ext'])) { echo 'value="' . $this->params['phone_ext'] . '"'; }?> maxlength="4" size="4" />
				<label for="phone_primary" class="no-float">Primary:</label>
				<input type="checkbox" id="phone_primary" name="phone_primary"
					<?php if (isset($this->params['phone_primary']) && $this->params['phone_primary']) { echo 'checked'; }?>
					<?php if (!isset($this->params['phone']) || is_null($this->params['phone'])) { echo 'disabled'; }?> />
			</div>
			<?php if (isset($this->errors['phone'])) { ?><div class="error-wrapper"><?php echo $this->errors['phone']; ?></div><?php } ?>
			<div class="form-wrapper">
				<label for="communication_type_id">Cell Carrier:</label>
				<select name="communication_type_id">
					<option></option>
					<?php 
					
					foreach ($this->commTypes() as $item) {
	 
						if (isset($this->params['communication_type_id']) && $this->params['communication_type_id'] === $item->getCommunication_type_id()) {
							
							echo '<option value="' . $item->getCommunication_type_id() . '" selected>' . $item->getCommunication_type() . '</option>';
						}
						else {
							
							echo '<option value="' . $item->getCommunication_type_id() . '">' . $item->getCommunication_type() . '</option>';
						}
	    			}
	    		
	    			?>
				</select>
			</div>
			<?php if (isset($this->errors['communication_type_id'])) { ?><div class="error-wrapper"><?php echo $this->errors['communication_type_id']; ?></div><?php } ?>
			<div class="form-wrapper">
				<label for="cell_phone">Cell #:</label>
				<input type="text" id="cell_phone" name="cell_phone" class="numeric phone" 
					<?php if (isset($this->params['cell_phone'])) { echo 'value="' . $this->params['cell_phone'] . '"'; }?> />
				<label for="cell_phone_primary" class="no-float">Primary:</label>
				<input type="checkbox" id="cell_phone_primary" name="cell_phone_primary"
					<?php if (isset($this->params['cell_phone_primary']) && $this->params['cell_phone_primary']) { echo 'checked'; }?>					
					<?php if (!isset($this->params['cell_phone']) || is_null($this->params['cell_phone'])) { echo 'disabled'; }?> />
			</div>
			<?php if (isset($this->errors['cell_phone'])) { ?><div class="error-wrapper"><?php echo $this->errors['cell_phone']; ?></div><?php } ?>
		</div>
	</div>	
	<div class="form-wrapper form-controls">
		<input type="submit" value="<?php echo ucfirst($this->type); ?> Employee" />
	</div>
</form>