<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/employees/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />

<table class="tableh" width="2500">
	<thead>
		<tr>
			<th column="tbl_employee.first_name">
				<div class="header">First Name</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.last_name">
				<div class="header">Last Name</div>
				<div class="sort asc"></div>
			</th>
			<th column="tbl_employee.addr">
				<div class="header">Address</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.addr2">
				<div class="header">Address Line 2</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.city">
				<div class="header">City</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.state">
				<div class="header">State</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.zip">
				<div class="header">Zip</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.vehicle_id">
				<div class="header">Vehicle ID</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_role.role_name">
				<div class="header">Role</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.active">
				<div class="header">Active</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.email">
				<div class="header">E-mail</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.phone">
				<div class="header">Phone</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.phone_ext">
				<div class="header">Phone Ext.</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.phone_primary">
				<div class="header">Phone Primary</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.cell_phone">
				<div class="header">Cell Phone</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_employee.cell_phone_primary">
				<div class="header">Cell Phone Primary</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_communication_type.communication_type">
				<div class="header">Cell Carrier</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/employees/tabulardata.phtml', array('employees' => $this->employees)); ?>
</table>