<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Address Line 2</th>
			<th>City</th>
			<th>State</th>
			<th>Zip</th>
			<th>Vehicle ID</th>
			<th>Role</th>
			<th>Active</th>
			<th>Email</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->emps as $item) { ?>	
		<tr>
			<td><?php echo $item->getFirst_name() . ' ' . $item->getLast_name(); ?></td>
			<td><?php echo $item->getAddr(); ?></td>
			<td><?php echo $item->getAddr2(); ?></td>
			<td><?php echo $item->getCity(); ?></td>
			<td><?php echo $item->getState(); ?></td>
			<td><?php if (strlen($item->getZip4()) === 0) { echo $item->getZip(); } else { echo $item->getZip() . '-' . $item->getZip4(); } ?></td>
			<td><?php echo $item->getVehicle_id(); ?></td>
			<td><?php echo $this->roles[$item->getRole_id()]->getRole_name(); ?></td>
			<td><?php echo $item->getActive(); ?></td>
			<td><?php echo $item->getEmail(); ?></td>
			<td><a href="/employees/edit/emp_id/<?php echo $item->getEmp_id(); ?>">Edit</a></td>
			<td><a href="/employees/delete/emp_id/<?php echo $item->getEmp_id(); ?>">Delete</a></td>
		</tr>
	<?php } ?>
	</tbody>
</table>