<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/employees/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />

<table class="tableh">
	<thead>
		<tr>
			<th column="e.first_name">
				<div class="header">First Name</div>
				<div class="sort"></div>
			</th>
			<th column="e.last_name">
				<div class="header">Last Name</div>
				<div class="sort asc"></div>
			</th>
			<th column="e.addr">
				<div class="header">Address</div>
				<div class="sort"></div>
			</th>
			<th column="e.addr2">
				<div class="header">Address Line 2</div>
				<div class="sort"></div>
			</th>
			<th column="e.city">
				<div class="header">City</div>
				<div class="sort"></div>
			</th>
			<th column="e.state">
				<div class="header">State</div>
				<div class="sort"></div>
			</th>
			<th column="e.zip">
				<div class="header">Zip</div>
				<div class="sort"></div>
			</th>
			<th column="e.vehicle_id">
				<div class="header">Vehicle ID</div>
				<div class="sort"></div>
			</th>
			<th column="r.role_name">
				<div class="header">Role</div>
				<div class="sort"></div>
			</th>
			<th column="e.active">
				<div class="header">Active</div>
				<div class="sort"></div>
			</th>
			<th column="e.email">
				<div class="header">E-mail</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/employees/tabulardata.phtml', array('employees' => $this->employees)); ?>
</table>