<script>
$(function() {

	$('#cancel').click(function(e) {

		e.preventDefault();
		window.location = '/reminders/view';
	});
});
</script>
<link rel="stylesheet" href="/css/reminders/reminders.css" />

<div class="form-header">Are you sure you want to delete the following Reminder?</div>
<form id="reminders-delete-form" class="delete" action="/reminders/delete/reminder_id/<?php echo $this->reminder->getReminder_id(); ?>" method="post">
	<div class="form-wrapper">
		<label>Reminder Type:</label>
		<?php echo $this->reminder->getReminder_type(); ?>
	</div>
	<div class="form-wrapper">
		<label>Asset Name:</label>
		<?php echo $this->reminder->getAsset_name(); ?>
	</div>
	<div class="form-wrapper">
		<label>Due Date:</label>
		<?php echo $this->reminder->getDue_date(); ?>
	</div>
	<div class="form-wrapper">
		<label>Completed Date:</label>
		<?php if (strlen($this->reminder->getCompleted_date()) > 0) { echo $this->reminder->getCompleted_date(); } else { echo 'N/A'; } ?>
	</div>
	<div class="form-wrapper">
		<label>Notes:</label>
		<?php if (strlen($this->reminder->getNotes()) > 0) { echo $this->reminder->getNotes(); } else { echo 'N/A'; } ?>
	</div>
	<div class="form-wrapper form-controls">
		<input type="submit" value="Delete" />
		<input id="cancel" type="button" value="Cancel" />
	</div>
</form>