<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/reminders/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />

<h3>Due in the next 30 days:</h3>
<br />
<table class="tableh">
	<thead>
		<tr>
			<th column="rt.reminder_type">
				<div class="header">Reminder Type</div>
				<div class="sort"></div>
			</th>
			<th column="at.asset_type">
				<div class="header">Asset Type</div>
				<div class="sort"></div>
			</th>
			<th column="a.asset_name">
				<div class="header">Asset Name</div>
				<div class="sort"></div>
			</th>
			<th column="r.due_date">
				<div class="header">Due Date</div>
				<div class="sort asc"></div>
			</th>
			<th column="r.completed_date">
				<div class="header">Completed Date</div>
				<div class="sort"></div>
			</th>
			<th column="r.notes">
				<div class="header">Notes</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="copy"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/reminders/tabulardata.phtml', array('reminders' => $this->reminders)); ?>
</table>