<?php $customertype = $this->customertypes(array('return'=>'arrayid'));
$cust_name = $customertype[$this->params['customer_type_id']]['customer_type'];
?>
<script type="text/javascript" src="/js/plugins/mColorPicker.min.js"></script>
<link rel="stylesheet" href="/css/reminders/reminders.css" />

<form id="customer-form" action="/customer/<?php echo $this->type; ?>" method="post">
	<?php if ($this->type === 'edit') { ?><input type="hidden" name="customer_id" value="<?php echo $this->id; ?>" /><?php } ?>
	<?php //if ($this->type === 'edit') { ?><input type="hidden" name="customer_type_id" value="<?php echo $this->params['customer_type_id']; ?>" /><?php // } ?>
	<div class="form-wrapper">
		<label for="name"><?php echo $cust_name;?> Name:</label>
		<input type="text" name="name" <?php if(isset($this->params['name'])&& !isset($this->errors)){echo 'value="'.$this->params['name'].'"';} ?>
										<?php if(isset($this->params['name'])&& isset($this->errors)){echo 'value="'.$this->params['name'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['name'])) { ?><div class="error-wrapper"><?php echo $this->errors['name']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="addr">Address:</label>
		<input type="text" name="addr" <?php if(isset($this->params['addr'])&& !isset($this->errors)){echo 'value="'.$this->params['addr'].'"';} ?>
										<?php if(isset($this->params['addr'])&& isset($this->errors)){echo 'value="'.$this->params['addr'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['addr'])) { ?><div class="error-wrapper"><?php echo $this->errors['addr']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="addr2">Address 2:</label>
		<input type="text" name="addr2" <?php if(isset($this->params['addr2'])&& !isset($this->errors)){echo 'value="'.$this->params['addr2'].'"';} ?>
										<?php if(isset($this->params['addr2'])&& isset($this->errors)){echo 'value="'.$this->params['addr2'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['addr2'])) { ?><div class="error-wrapper"><?php echo $this->errors['addr2']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="city">City:</label>
		<input type="text" name="city" <?php if(isset($this->params['city'])&& !isset($this->errors)){echo 'value="'.$this->params['city'].'"';} ?>
										<?php if(isset($this->params['city'])&& isset($this->errors)){echo 'value="'.$this->params['city'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['city'])) { ?><div class="error-wrapper"><?php echo $this->errors['city']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="state">State:</label>
		<input type="text" name="state" <?php if(isset($this->params['state'])&& !isset($this->errors)){echo 'value="'.$this->params['state'].'"';} ?>
										<?php if(isset($this->params['state'])&& isset($this->errors)){echo 'value="'.$this->params['state'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['state'])) { ?><div class="error-wrapper"><?php echo $this->errors['state']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="zip">Zip:</label>
		<input type="text" name="zip" <?php if(isset($this->params['zip'])&& !isset($this->errors)){echo 'value="'.$this->params['zip'].'"';} ?>
										<?php if(isset($this->params['zip'])&& isset($this->errors)){echo 'value="'.$this->params['zip'].'"';} ?>/>
		<input type="text" name="zip4" <?php if(isset($this->params['zip4'])&& !isset($this->errors)){echo 'value="'.$this->params['zip4'].'"';} ?>
										<?php if(isset($this->params['zip4'])&& isset($this->errors)){echo 'value="'.$this->params['zip4'].'"';} ?>/>								
	</div>
	<?php if (isset($this->errors['zip'])) { ?><div class="error-wrapper"><?php echo $this->errors['zip']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="fein">FEIN:</label>
		<input type="text" name="fein" <?php if(isset($this->params['fein'])&& !isset($this->errors)){echo 'value="'.$this->params['fein'].'"';} ?>
										<?php if(isset($this->params['fein'])&& isset($this->errors)){echo 'value="'.$this->params['fein'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['fein'])) { ?><div class="error-wrapper"><?php echo $this->errors['state']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="color_code">Color:</label>
		<input data-text="hidden"  data-hex="true" type="color" name="color_code" <?php if(isset($this->params['color_code'])&& !isset($this->errors)){echo 'value="'.$this->params['color_code'].'"';} ?>
										<?php if(isset($this->params['color_code'])&& isset($this->errors)){echo 'value="'.$this->params['color_code'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['color_code'])) { ?><div class="error-wrapper"><?php echo $this->errors['color_code']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="notes">Notes:</label>
		<textarea name="notes"><?php if (isset($this->params['notes'])) { echo $this->params['notes']; } ?></textarea>
	</div>
	<?php if (isset($this->errors['notes'])) { ?><div class="error-wrapper"><?php echo $this->errors['notes']; ?></div><?php } ?>
	
	<div class="form-wrapper form-controls">
		<input type="submit" value="<?php echo ucfirst($this->type); ?> <?php if(isset($this->params['name'])){ echo ' '.$this->params['name'];}?>" />
	</div>

</form>