<link rel="stylesheet" href="/css/tableh.css" />
<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/customer/tabulardata/customertype/<?php echo $this->customertype;?>' });
});
</script>
<?php $customertype = $this->customertypes(array('return'=>'arrayid'));
?>
<h3>
	<?php echo $this->header.' ';
		  echo $customertype[$this->customertype]['customer_type'];?>
s</h3>
<div class="table-controls" >
<ul >
	<li>
		<a href="/customer/view/customertype/<?php echo $this->customertype?>/active/<?php if($this->active==1){echo 0;}else{echo 1;} ?>">
		<?php if($this->active==1){echo 'Show inactive';}else{echo 'Show active';}?>
		</a>
	</li>
	
	<li>
	<a href="/customer/add/customertype/<?php echo $this->customertype?>">Add</a>
	</li>
</ul>
</div>
<div style=clear:both"></div>

<table class="tableh">
	<thead>
		<tr>
			<th column="c1.name">
				<div class="header"><?php echo $customertype[$this->customertype]['customer_type'];?> Name</div>
				<div class="sort"></div>
			</th>
			<th column="c1.address">
				<div class="header">Address</div>
				<div class="sort"></div>
			</th>
			<th column="c1.city">
				<div class="header">City</div>
				<div class="sort"></div>
			</th>
			<th column="c1.state">
				<div class="header">State</div>
				<div class="sort"></div>
			</th>
			<th column="c1.zip">
				<div class="header">Zip</div>
				<div class="sort"></div>
			</th>
			<th column="c1.fein">
				<div class="header">FEIN</div>
				<div class="sort"></div>
			</th>
			<th column="c1.color">
				<div class="header">Color</div>
				<div class="sort"></div>
			</th>
			<th>Show Contacts</th>
			<th>Edit</th>
			<th></th>
			<th><?php if($this->active==1){echo 'De-Activate';}else{echo 'Activate';} ?></th>
		</tr>
	</thead>
	<?php echo $this->partial('/customer/tabulardata.phtml', array('data' => $this->data)); ?>
</table>