
<?php $customertype = $this->customertypes(array('return'=>'arrayid'));
?>
<h3>
	<?php echo $this->header.' ';
		  echo $customertype[$this->customertype]['customer_type'];?>
s</h3>
<div>
	<a href="/customer/view/customertype/<?php echo $this->customertype?>/active/<?php if($this->active==1){echo 0;}else{echo 1;} ?>">
		<?php if($this->active==1){echo 'Show inactive';}else{echo 'Show active';}?>
	</a>
</div>
<div>
	<a href="/customer/add/customertype/<?php echo $this->customertype?>">Add</a>
</div>
<table>
	<thead>
		<tr>
			<th><?php echo $customertype[$this->customertype]['customer_type'];?> Name</th>
			<th>Address</th>
			<th>City</th>
			<th>State</th>
			<th>Zip</th>
			<th>FEIN</th>
			<th>Color</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->data as $item) { ?>
		<tr>
			<td><?php echo $item->getName();?></td>
			<td><?php echo $item->getAddr(); ?></td>
			<td><?php echo $item->getCity(); ?></td>
			<td><?php echo $item->getState(); ?></td>
			<td><?php echo $item->getZip();if($item->getZip4()!= null){echo '-'.$item->getZip4();} ?></td>
			<td><?php echo $item->getFEIN(); ?></td>
			<td><div class="color_code"  style="width:100px;height:20px;background-color:<?php echo '#'.$item->getColor_Code();?>;">&nbsp;</div></td>
			<td><a href="/customercontact/view/customerid/<?php echo $item->getCustomer_id(); ?>">Show Contacts</a></td>
			<td><a href="/customer/edit/customerid/<?php echo $item->getCustomer_id(); ?>">Edit</a></td>
			<td><!--<a href="/customer/delete/customerid/<?php echo $item->getCustomer_id(); ?>">Delete</a>--></td>
			<td><a href="/customer/active/customerid/<?php echo $item->getCustomer_id(); ?>/active/<?php if($item->getActive()==1){echo 0;}else{echo 1;}?>/customertype/<?php echo $this->customertype?>"><?php if($item->getActive()==1){echo 'De-Activate';}else{echo 'Activate';} ?></a></td>
		</tr>
	<?php } ?>
	</tbody>
</table>