<div id="leftnav">
	<ul class="sf-menu sf-vertical sf-js-enabled sf-shadow">
		<li>
			<a class="sf-with-ul">Standard Loads</a>
			<ul style="display: none; visibility: hidden;">
				<li>
					<a href="/standardloads/create">Create</a>
				</li>
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">My Account</a>
			<ul style="display: none; visibility: hidden;">
				<li>
					<a href="/myaccount/changepass">Change Password</a>
				</li>
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">Employees</a>
			<ul style="display: none; visibility: hidden;">
				<li>
					<a href="/employees/create">Create</a>
				</li>
				<li>
					<a href="/employees/modify">Modify</a>
				</li>
			</ul>
		</li>
	</ul>
</div>