<div id="nav">			
	<ul class="sf-menu sf-js-enabled sf-shadow">
		<li class="current">
			<a class="sf-with-ul">My Account <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/myaccount/changepass">Change Password</a></li>
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">Drivers &amp; Employees <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/employees/add">Add</a></li>							
				<li><a href="/employees/view">View</a></li>							
			</ul>
		</li>	
		<li>
			<a class="sf-with-ul">Reminders <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/reminders/add">Add</a></li> 					
				<li><a href="/reminders/view">View</a></li> 
				<li><a class="sf-with-ul">Reminder Types <span class="sf-sub-indicator"> »</span></a>
					<ul style="display: none; visibility: hidden;">
						<li><a href="/remindertypes/add">Add</a></li>
						<li><a href="/remindertypes/view">View</a></li> 							
					</ul>	
				</li>										
			</ul>
		</li>	
		<li>
			<a class="sf-with-ul">Assets <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/assets/add">Add</a></li> 					
				<li><a href="/assets/view">View</a></li> 
				<li><a class="sf-with-ul">Asset Types <span class="sf-sub-indicator"> »</span></a>
					<ul style="display: none; visibility: hidden;">
						<li><a href="/assettypes/add">Add</a></li>
						<li><a href="/assettypes/view">View</a></li> 							
					</ul>	
				</li>										
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">Customers <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/customer/view/customertype/1">Bill To</a></li>
				<li><a href="/customer/view/customertype/2">Shipper</a></li>
				<li><a href="/customer/view/customertype/3">Customers</a></li>
				<li><a href="/customer/view/customertype/4">Origins</a></li>
				<li><a href="/customer/view/customertype/5">Destinations</a></li>
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">Rates <span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/rates/add">Add</a></li>
				<li><a href="/rates/search">Search</a></li>
				<li><a href="/rates/view?today">Show Todays</a></li>
				<li><a href="/rates/view">Show All</a></li>
			</ul>
		</li>
		<li>
			<a class="sf-with-ul">Fuel Surcharge<span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/fuelsurcharge/add">Add</a></li>
				<li><a href="/fuelsurcharge/search">Search</a></li>
<!--				<li><a href="/fuelsurcharge/view?today">Show Todays</a></li>-->
				<li><a href="/fuelsurcharge/view">Show All</a></li>
			</ul>
		</li>	
		<li>
			<a class="sf-with-ul">Standard Loads<span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/standardloads/add">Add</a></li>
				<li><a href="/standardloads/add/multiple/1">Add Multiple</a></li>
				<li><a href="/standardloads/view">View</a></li>
			</ul>
		</li>	
		<li>
			<a class="sf-with-ul">Carrier Discounts<span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/carrierdiscounts/add">Add</a></li>
				<li><a href="/carrierdiscounts/view">View</a></li>
			</ul>
		</li>	
		
		<li>
			<a class="sf-with-ul" href="/dispatch/view">Dispatch<!-- <span class="sf-sub-indicator"> »</span>--></a>
<!--			<ul style="display: none; visibility: hidden;">-->
<!--				<li><a href="/carrierdiscounts/add">Add</a></li>-->
<!--				<li><a href="/carrierdiscounts/view">View</a></li>-->
<!--			</ul>-->
		</li>
		<li>
			<a class="sf-with-ul">QuickBooks<span class="sf-sub-indicator"> »</span></a>
			<ul style="display: none; visibility: hidden;">
				<li><a href="/quickbooks/verifyloads">Verify Loads</a></li>
			</ul>
		</li>
	</ul>
</div>