<!doctype html> 
<html>
<head>
	<title>LLL Transport</title>
	<script src="/js/jquery.min.js"></script>
	<script src="/js/jquery-ui-1.8.9.custom.min.js"></script>
	<script src="/js/superfish/hoverIntent.js"></script> 
	<script src="/js/superfish/superfish.js"></script>
	<script src="/js/alphanumeric/jquery.alphanumeric.pack.js"></script>
	<script src="/js/maskedinput/jquery.maskedinput-1.2.2.min.js"></script>
	<script src="/js/script.js"></script>
	<link rel="stylesheet" href="/css/ui-lightness/jquery-ui-1.8.9.custom.css">
	<link rel="stylesheet" href="/css/reset.css">
	<link rel="stylesheet" href="/css/style.css">
</head>
<body>
	<?php echo $this->render('public-header.phtml') ?>
	<?php echo $this->render('content.phtml') ?>
</body>
</html>