<div id="topnav">			
	<ul>
		<li><div class="tab <?php if ($this->layout()->pageTitle === 'Home') { echo 'selected'; } ?>"><a href="/index">Home</a></div></li>
		<li><div class="tab <?php if ($this->layout()->pageTitle === 'Standard Loads') { echo 'selected'; } ?>"><a href="/standardloads">Standard Loads</a></div></li>
		<li><div class="tab <?php if ($this->layout()->pageTitle === 'Dispatch') { echo 'selected'; } ?>"><a href="/dispatch">Dispatch</a></div></li>
		<li><div class="tab <?php if ($this->layout()->pageTitle === 'Load Counts') { echo 'selected'; } ?>"><a href="/loadcounts">Load Counts</a></div></li>
	</ul>
</div>