<script>
$(function() {

	$('#cancel').click(function(e) {

		e.preventDefault();
		window.location = '/remindertypes/view';
	});
});
</script>
<link rel="stylesheet" href="/css/remindertypes/remindertypes.css" />

<div class="form-header">Are you sure you want to delete the following Reminder Type?</div>
<form id="remindertypes-delete-form" class="delete" action="/remindertypes/delete/reminder_type_id/<?php echo $this->params['reminder_type_id']; ?>" method="post">
	<div class="form-wrapper">
		<label>Reminder Type:</label>
		<?php echo $this->reminderType->getReminder_type(); ?>
	</div>
	<div class="form-wrapper">
		<label>Active:</label>
		<?php echo $this->reminderType->getActive(); ?>
	</div>	
	<div class="form-wrapper">
		<label>Description:</label>
		<?php if (strlen($this->reminderType->getDescription()) > 0) { echo $this->reminderType->getDescription(); } else { echo 'N/A'; } ?>
	</div>
	<div class="form-wrapper">
		<label>Asset or Employee:</label>
		<?php echo ucfirst($this->reminderType->getAsset_or_employee()); ?>
	</div>
	<div class="form-wrapper form-controls">
		<input type="submit" value="Delete" />
		<input id="cancel" type="button" value="Cancel" />
	</div>
</form>