<script src="/js/tableh.js"></script>
<script>
$(document).ready(function() {
	
	$('.tableh').tableh({ 'url': '/remindertypes/tabulardata' });
});
</script>
<link rel="stylesheet" href="/css/tableh.css" />


<table class="tableh">
	<thead>
		<tr>
			<th column="tbl_reminder_type.reminder_type">
				<div class="header">Reminder Type</div>
				<div class="sort asc"></div>
			</th>
			<th column="tbl_reminder_type.active">
				<div class="header">Active</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_reminder_type.description">
				<div class="header">Description</div>
				<div class="sort"></div>
			</th>
			<th column="tbl_reminder_type.asset_or_employee">
				<div class="header">Asset or Employee</div>
				<div class="sort"></div>
			</th>
			<th class="edit"></th>
			<th class="delete"></th>
		</tr>
	</thead>
	<?php echo $this->partial('/remindertypes/tabulardata.phtml', array('reminderTypes' => $this->reminderTypes)); ?>
</table>