<?php
$contact = $this->contact_data;
//var_dump($this->contact_data);
?>
<div id="contact-list">
	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Phone</th>
				<th>Cell Phone</th>
				<th>Fax</th>
				<th>Email</th>
				<th>Notes</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($contact as $row)
			{?>
				<tr>
					<td><?php echo $row['first_name'].' '. $row['last_name'] ?></td>
					<td><?php echo $row['phone']; if(strlen($row['phone_ext'])>0){echo ' ext:'.  $row['phone_ext'];}?></td>
					<td><?php echo $row['cell_phone'];?></td>
					<td><?php echo $row['fax_phone'];?></td>
					<td><?php echo $row['email'];?></td>
					<td><?php echo $row['notes'];?></td>
					<td><a class="edit-customercontact" href="customercontact?_method=update&_contact_id=<?php echo $row['contact_id'];?>">edit</a></td>
					<td><a class="delete-customercontact" href="customercontact?_method=update&_contact_id=<?php echo $row['contact_id'];?>">delete</a></td>
				</tr>
			<?php }?>
		</tbody>
	</table>
	<button id="add-contact-button">Add Contact</button>
</div>

<script>var contact_data = <?php json_encode($this->contact_data);?>;</script>