
<script type="text/javascript" src="/js/plugins/mColorPicker.min.js"></script>
<link rel="stylesheet" href="/css/reminders/reminders.css" />
<form id="customer-form" action="/customercontact/<?php echo $this->type; ?>" method="post">
	<?php if ($this->type === 'edit') { ?><input type="hidden" name="contact_id" value="<?php echo $this->id; ?>" /><?php } ?>
	<?php if ($this->type === 'add') { ?><input type="hidden" name="customer_id" value="<?php echo $this->params['customerid']; ?>" /><?php  } ?>
	<div class="form-wrapper">
		<label for="first_name">First Name:</label>
		<input type="text" name="first_name" <?php if(isset($this->params['first_name'])&& !isset($this->errors)){echo 'value="'.$this->params['first_name'].'"';} ?>
										<?php if(isset($this->params['first_name'])&& isset($this->errors)){echo 'value="'.$this->params['first_name'].'"';} ?>/>
	</div>
	
	<?php if (isset($this->errors['last_name'])) { ?><div class="error-wrapper"><?php echo $this->errors['last_name']; ?></div><?php } ?>
	
		<div class="form-wrapper">
		<label for="last_name">Last Name:</label>
		<input type="text" name="last_name" <?php if(isset($this->params['last_name'])&& !isset($this->errors)){echo 'value="'.$this->params['last_name'].'"';} ?>
										<?php if(isset($this->params['last_name'])&& isset($this->errors)){echo 'value="'.$this->params['last_name'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['last_name'])) { ?><div class="error-wrapper"><?php echo $this->errors['last_name']; ?></div><?php } ?>	
	
	<div class="form-wrapper">
		<label for="phone">Phone:</label>
		<input type="text" name="phone" <?php if(isset($this->params['phone'])&& !isset($this->errors)){echo 'value="'.$this->params['phone'].'"';} ?>
										<?php if(isset($this->params['phone'])&& isset($this->errors)){echo 'value="'.$this->params['phone'].'"';} ?>/>
										
		<input type="text" name="phone_ext" <?php if(isset($this->params['phone_ext'])&& !isset($this->errors)){echo 'value="'.$this->params['phone_ext'].'"';} ?>
										<?php if(isset($this->params['phone_ext'])&& isset($this->errors)){echo 'value="'.$this->params['phone_ext'].'"';} ?>/>
	</div>
	
	<div class="form-wrapper">
		<label for="cell_phone">Cell phone:</label>
		<input type="text" name="cell_phone" <?php if(isset($this->params['cell_phone'])&& !isset($this->errors)){echo 'value="'.$this->params['cell_phone'].'"';} ?>
										<?php if(isset($this->params['cell_phone'])&& isset($this->errors)){echo 'value="'.$this->params['cell_phone'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['cell_phone'])) { ?><div class="error-wrapper"><?php echo $this->errors['cell_phone']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="fax_phone">Fax:</label>
		<input type="text" name="fax_phone" <?php if(isset($this->params['fax_phone'])&& !isset($this->errors)){echo 'value="'.$this->params['fax_phone'].'"';} ?>
										<?php if(isset($this->params['fax_phone'])&& isset($this->errors)){echo 'value="'.$this->params['fax_phone'].'"';} ?>/>
	</div>
	<?php if (isset($this->errors['fax_phone'])) { ?><div class="error-wrapper"><?php echo $this->errors['fax_phone']; ?></div><?php } ?>
	
	<div class="form-wrapper">
		<label for="email">Fax:</label>
		<input type="text" name="email" <?php if(isset($this->params['email'])&& !isset($this->errors)){echo 'value="'.$this->params['email'].'"';} ?>
										<?php if(isset($this->params['email'])&& isset($this->errors)){echo 'value="'.$this->params['email'].'"';} ?>/>
	</div>
	
	
	<?php if (isset($this->errors['fax_phone'])) { ?><div class="error-wrapper"><?php echo $this->errors['fax_phone']; ?></div><?php } ?>

	
	<div class="form-wrapper">
		<label for="notes">Notes:</label>
		<textarea name="notes"><?php if (isset($this->params['notes'])) { echo $this->params['notes']; } ?></textarea>
	</div>
	<?php if (isset($this->errors['notes'])) { ?><div class="error-wrapper"><?php echo $this->errors['notes']; ?></div><?php } ?>
	
	<div class="form-wrapper form-controls">
		<input type="submit" value="<?php echo ucfirst($this->type); ?> <?php if(isset($this->params['name'])){ echo ' '.$this->params['name'];}?>" />
	</div>

</form>