
<h3>
	<?php echo 'Contacts for  ';
		  echo $this->customername;?>
</h3>
<div>
	<a href="/customercontact/view/customerid/<?php echo $this->customerid?>/active/<?php if($this->active==1){echo 0;}else{echo 1;} ?>">
		<?php if($this->active==1){echo 'Show inactive';}else{echo 'Show active';}?>
	</a>
</div>
<div>
	<a href="/customercontact/add/customerid/<?php echo $this->customerid?>">Add</a>
</div>
<?php if(is_array($this->data)) {?>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Phone</th>
			<th>Cell Phone</th>
			<th>Fax</th>
			<th>Email</th>
			<th>Notes</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->data as $item) { ?>
		<tr>
			<td><?php echo $item->getFirst_Name(). ' ' .$item->getLast_Name();?></td>
			<td><?php echo $item->getPhone();if($item->getPhone_ext()!=null){echo ' ext ' . $item->getPhone_ext();} ?></td>
			<td><?php echo $item->getCell_phone(); ?></td>
			<td><?php echo $item->getFax_phone(); ?></td>
			<td><?php if($item->getEmail()!=null){?><a href="mailto:<?php echo $item->getEmail(); ?>"<?php echo $item->getEmail();?></a><?php }?></td>
			<td><?php echo $item->getNotes(); ?></td>
			<td></td>
			<td></td>
			<td><a href="/customercontact/edit/contactid/<?php echo $item->getContact_id(); ?>/customerid/<?php echo $this->customerid ?>">Edit</a></td>
			<td></td>
			<td><a href="/customercontact/active/contactid/<?php echo $item->getContact_id(); ?>/active/<?php if($item->getActive()==1){echo 0;}else{echo 1;}?>/customerid/<?php echo $this->customerid?>"><?php if($item->getActive()==1){echo 'De-Activate';}else{echo 'Activate';} ?></a></td>
		</tr>
	<?php } ?>
	</tbody>
</table>
<?php }?>